// Generated by tools/make-scenario.py from tools/scenarios/tel-azeka.json — do
// not edit by hand; change the spec and rerun the tool. The ground it is laid
// on is generated too, by tools/fetch-dtm.py and tools/fetch-osm.py.
// Written 2026-09-16.

import { Game, makeCommandGroup, makeInfantry, makeVehicle, type Terrain } from "../../engine/index.js";
import type { Scenario } from "./types.js";
import { TEL_AZEKA } from "../maps/telAzeka.js";
import { TEL_AZEKA_OBJECTS, TEL_AZEKA_ROADS } from "../maps/telAzekaObjects.js";

/**
 * Tel Azeka over the Elah valley (תל עזקה, עמק האלה): the tel stands at 345 m in the middle of the window, its eastern face falling 110 m to the valley floor, a ridge running south from it and low ground in the east.
 * 1200 × 1000 m centred on 31.69850 N, 34.93550 E, north up.
 */
export function buildTelAzekaTerrain(): Terrain {
  return { heightfield: TEL_AZEKA, objects: TEL_AZEKA_OBJECTS, roads: TEL_AZEKA_ROADS };
}

/**
 * A BLUE platoon taking the tel from the south, against a RED platoon holding
 * it. The ground here teaches the opposite half of what the Yokneam demo
 * teaches, and it teaches it with relief alone: this window holds one tree and
 * no buildings at all, so nothing is in cover that the shape of the hill does
 * not put there.
 *
 * **The covered route is the expensive one.** The tel's eastern face is dead
 * ground — a force climbing it is unseen from the summit until it is 700 m in
 * — but it is a 110 m climb, and Naismith charges 8 m of the bound for every
 * metre of it (rules decision 15): 100 m of that face costs a squad between
 * 250 and 360 m of its movement budget, which is five to seven turns of
 * walking. The southern ridge is the other way up: nearly level, so a bound
 * buys the distance it measures — and in view of the summit for its whole
 * length. The player is choosing between being seen and being slow, and the
 * map says which is which before a shot is fired: the drawn reach shrinks to
 * almost nothing pointed up the face.
 *
 * The one piece of dead ground close in is the saddle at about (610, 450),
 * 100 m below the summit and out of sight of every RED position — the only
 * place an assault can form up. Which is why RED has mined it.
 *
 * RED's third squad sits on the northern spur watching the valley, the
 * approach BLUE has not taken. That is a third of the defence committed to
 * the wrong ground, and it is the only RED force that sees the valley floor —
 * so a feint east is worth something.
 */
export function buildTelAzekaScenario(seed = 1948): Scenario {
  const game = new Game({
    seed,
    trackIntel: true,
    enforceC2: true,
    terrain: buildTelAzekaTerrain(),
  });

  game.addUnit(makeInfantry("BLUE-1", "BLUE", "squad", { x: 450, y: 950 }, 8, "כיתה 1"));
  game.addUnit(makeInfantry("BLUE-2", "BLUE", "squad", { x: 520, y: 930 }, 8, "כיתה 2"));
  // The left-hand squad, from which the valley is reachable if the player would rather feint east than climb.
  game.addUnit(makeInfantry("BLUE-3", "BLUE", "squad", { x: 390, y: 900 }, 8, "כיתה 3"));
  game.addUnit(makeCommandGroup("BLUE-HQ", "BLUE", "platoon", { x: 470, y: 980 }, 3, "חפ\"ק מ\"מ"));
  // On the summit: it sees the whole southern ridge and none of its own eastern face.
  game.addUnit(makeInfantry("RED-1", "RED", "squad", { x: 620, y: 350 }, 8, "מחלקה ב'/1"));
  // On the shoulder above the ridge, in a position prepared before the battle: it covers the southern approach from 750 m in.
  // Dressed before it is added: addUnit records a force as it stands, so
  // a force camouflaged or covered after the fact would replay undressed.
  const red2 = makeInfantry("RED-2", "RED", "squad", { x: 560, y: 560 }, 8, "מחלקה ב'/2");
  red2.baseCover = "partial";
  game.addUnit(red2);
  // On the northern spur, the only RED force that sees the valley floor — and, if BLUE comes up the ridge, the one watching the wrong ground.
  game.addUnit(makeInfantry("RED-3", "RED", "squad", { x: 700, y: 250 }, 6, "מחלקה ב'/3"));
  // Behind the summit, within 300 m of all three squads: this platoon is in contact every turn, which the attacker's will not be for long.
  game.addUnit(makeCommandGroup("RED-HQ", "RED", "platoon", { x: 560, y: 280 }, 3, "חפ\"ק מ\"מ"));

  // Emplaced in setup, which is the only time a charge is placed rather
  // than laid by a force during the battle (rules decision 16).
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 600, y: 450 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 625, y: 460 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 590, y: 490 }, armed: true, detected: false });

  return { game, mapWidth: 1200, mapHeight: 1000, title: "עמק האלה — תפיסת תל עזקה" };
}
