// Generated by tools/make-scenario.py from tools/scenarios/tel-azeka-assault-2to1.json — do
// not edit by hand; change the spec and rerun the tool. The ground it is laid
// on is generated too, by tools/fetch-dtm.py and tools/fetch-osm.py.
// Written 2026-09-29.

import { Game, makeCommandGroup, makeInfantry, makeVehicle, type Terrain } from "../../engine/index.js";
import type { Scenario, ScenarioListing } from "./types.js";
import { TEL_AZEKA } from "../maps/telAzeka.js";
import { TEL_AZEKA_OBJECTS, TEL_AZEKA_ROADS } from "../maps/telAzekaObjects.js";

/**
 * Tel Azeka over the Elah valley (תל עזקה, עמק האלה): the tel stands at 345 m in the middle of the window, its eastern face falling 110 m to the valley floor, a ridge running south from it and low ground in the east.
 * 1200 × 1000 m centred on 31.69850 N, 34.93550 E, north up.
 */
export function buildTelAzekaAssault2Terrain(): Terrain {
  return { heightfield: TEL_AZEKA, objects: TEL_AZEKA_OBJECTS, roads: TEL_AZEKA_ROADS };
}

/**
 * The company battle's ground at the odds an attack is planned at: a BLUE
 * company against one RED platoon, three to one (author, 2026-09-28: play a
 * 3:1 battle). RED's first platoon holds the shoulder above the ridge in the
 * positions it prepared before the battle, as in the company battle; its
 * company command group is behind the summit and calls the company's
 * mortars for it. BLUE comes up from the south with three platoons abreast.
 * Both sides have the company mortar section on call all battle — twelve
 * missions a side, the fire rules decision 43 was calibrated on.
 *
 * ⚠️ The layout is ours, not the author's: the company battle's with RED's
 * second platoon taken away. The mines in the saddle are the platoon battle's.
 */
export function buildTelAzekaAssault2Scenario(seed = 1967): Scenario {
  const game = new Game({
    seed,
    trackIntel: true,
    enforceC2: true,
    morale: true,
    locationError: true,
    stillDetection: true,
    binoculars: true,
    keepEyesOn: true,
    commandSuccession: true,
    attackers: ["BLUE"],
    commandEchelon: { BLUE: "company", RED: "company" },
    fireSupport: {
      BLUE: [{ weapon: "mortar", missions: 12 }],
      RED: [{ weapon: "mortar", missions: 12 }],
    },
    terrain: buildTelAzekaAssault2Terrain(),
  });

  game.addUnit(makeCommandGroup("BLUE-COY", "BLUE", "company", { x: 600, y: 990 }, 5, "חפ\"ק מ\"פ"));
  game.addUnit(makeCommandGroup("BLUE-1-HQ", "BLUE", "platoon", { x: 430, y: 975 }, 3, "חפ\"ק מ\"מ 1"));
  game.addUnit(makeInfantry("BLUE-1-1", "BLUE", "squad", { x: 360, y: 940 }, 8, "כיתה 1/1"));
  game.addUnit(makeInfantry("BLUE-1-2", "BLUE", "squad", { x: 430, y: 930 }, 8, "כיתה 1/2"));
  game.addUnit(makeInfantry("BLUE-1-3", "BLUE", "squad", { x: 500, y: 940 }, 8, "כיתה 1/3"));
  game.addUnit(makeCommandGroup("BLUE-2-HQ", "BLUE", "platoon", { x: 640, y: 975 }, 3, "חפ\"ק מ\"מ 2"));
  game.addUnit(makeInfantry("BLUE-2-1", "BLUE", "squad", { x: 580, y: 930 }, 8, "כיתה 2/1"));
  game.addUnit(makeInfantry("BLUE-2-2", "BLUE", "squad", { x: 650, y: 925 }, 8, "כיתה 2/2"));
  game.addUnit(makeInfantry("BLUE-2-3", "BLUE", "squad", { x: 720, y: 935 }, 8, "כיתה 2/3"));
  // Behind the summit, on its northern side.
  game.addUnit(makeCommandGroup("RED-COY", "RED", "company", { x: 600, y: 200 }, 5, "חפ\"ק מ\"פ"));
  game.addUnit(makeCommandGroup("RED-A-HQ", "RED", "platoon", { x: 570, y: 430 }, 3, "חפ\"ק מ\"מ א'"));
  // The platoon battle's shoulder position, covering the southern approach.
  // Dressed before it is added: addUnit records a force as it stands, so
  // a force camouflaged or covered after the fact would replay undressed.
  const reda1 = makeInfantry("RED-A-1", "RED", "squad", { x: 560, y: 560 }, 8, "מחלקה א'/1");
  reda1.baseCover = "full";
  game.addUnit(reda1);
  const reda2 = makeInfantry("RED-A-2", "RED", "squad", { x: 650, y: 520 }, 8, "מחלקה א'/2");
  reda2.baseCover = "full";
  game.addUnit(reda2);
  const reda3 = makeInfantry("RED-A-3", "RED", "squad", { x: 470, y: 510 }, 8, "מחלקה א'/3");
  reda3.baseCover = "full";
  game.addUnit(reda3);

  // Emplaced in setup, which is the only time a charge is placed rather
  // than laid by a force during the battle (rules decision 16).
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 600, y: 450 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 625, y: 460 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 590, y: 490 }, armed: true, detected: false });

  return { game, mapWidth: 1200, mapHeight: 1000, title: "עמק האלה — שתי מחלקות מסתערות על מחלקה (2:1)" };
}

/** How the scenario picker offers this battle, before anything is built. */
export const telAzekaAssault2Listing: ScenarioListing = {
  id: "telAzekaAssault2",
  title: "עמק האלה — שתי מחלקות מסתערות על מחלקה (2:1)",
  brief: "כחול: שתי מחלקות תוקפות את כתף תל עזקה מדרום, ביחס של כ־2:1. אדום: מחלקה מחזיקה בכתף, בעמדות שהוכנו מראש. לבדיקה: האם מתקפה מתחת ל־3:1 על עמדות מוכנות יכולה להצליח.",
  mapWidth: 1200,
  mapHeight: 1000,
  build: buildTelAzekaAssault2Scenario,
};
