// Generated by tools/make-scenario.py from tools/scenarios/tel-azeka-company.json — do
// not edit by hand; change the spec and rerun the tool. The ground it is laid
// on is generated too, by tools/fetch-dtm.py and tools/fetch-osm.py.
// Written 2026-09-23.

import { Game, makeCommandGroup, makeInfantry, makeVehicle, type Terrain } from "../../engine/index.js";
import type { Scenario, ScenarioListing } from "./types.js";
import { TEL_AZEKA } from "../maps/telAzeka.js";
import { TEL_AZEKA_OBJECTS, TEL_AZEKA_ROADS } from "../maps/telAzekaObjects.js";

/**
 * Tel Azeka over the Elah valley (תל עזקה, עמק האלה): the tel stands at 345 m in the middle of the window, its eastern face falling 110 m to the valley floor, a ridge running south from it and low ground in the east.
 * 1200 × 1000 m centred on 31.69850 N, 34.93550 E, north up.
 */
export function buildTelAzekaCompanyTerrain(): Terrain {
  return { heightfield: TEL_AZEKA, objects: TEL_AZEKA_OBJECTS, roads: TEL_AZEKA_ROADS };
}

/**
 * The Tel Azeka ground at the next echelon up: a BLUE company taking the tel
 * from the south against a RED company holding it, each commanded at company
 * level, so each has its company mortars (rules decision 37) as fire missions
 * (decision 34) — four for the attacker, three for the defender. It is the
 * battle the planning stage (decision 38) and the call-for-fire control are
 * played on: both demo platoon battles have no indirect fire at all.
 *
 * RED holds the tel with two platoons. The first faces south on the shoulder
 * above the ridge, in positions prepared before the battle; the second holds
 * the summit, the northern spur and the eastern face. The company command
 * group is behind the summit. BLUE comes up with three platoons abreast: the
 * western one on the ridge, in view of the summit all the way; the eastern
 * one in the lower ground, from which the dead ground of the eastern face can
 * be reached. Neither side's plan is written here: registered targets,
 * observation posts and alternate positions are the players' to set before
 * the first turn.
 *
 * ⚠️ The layout is ours, not the author's. The mines in the saddle are the
 * platoon battle's.
 */
export function buildTelAzekaCompanyScenario(seed = 1949): Scenario {
  const game = new Game({
    seed,
    trackIntel: true,
    enforceC2: true,
    morale: true,
    commandEchelon: { BLUE: "company", RED: "company" },
    fireSupport: {
      BLUE: [{ weapon: "mortar", missions: 4 }],
      RED: [{ weapon: "mortar", missions: 3 }],
    },
    terrain: buildTelAzekaCompanyTerrain(),
  });

  game.addUnit(makeCommandGroup("BLUE-COY", "BLUE", "company", { x: 600, y: 990 }, 5, "חפ\"ק מ\"פ"));
  game.addUnit(makeCommandGroup("BLUE-1-HQ", "BLUE", "platoon", { x: 430, y: 975 }, 3, "חפ\"ק מ\"מ 1"));
  game.addUnit(makeInfantry("BLUE-1-1", "BLUE", "squad", { x: 360, y: 940 }, 8, "כיתה 1/1"));
  game.addUnit(makeInfantry("BLUE-1-2", "BLUE", "squad", { x: 430, y: 930 }, 8, "כיתה 1/2"));
  game.addUnit(makeInfantry("BLUE-1-3", "BLUE", "squad", { x: 500, y: 940 }, 8, "כיתה 1/3"));
  game.addUnit(makeCommandGroup("BLUE-2-HQ", "BLUE", "platoon", { x: 640, y: 975 }, 3, "חפ\"ק מ\"מ 2"));
  game.addUnit(makeInfantry("BLUE-2-1", "BLUE", "squad", { x: 580, y: 930 }, 8, "כיתה 2/1"));
  game.addUnit(makeInfantry("BLUE-2-2", "BLUE", "squad", { x: 650, y: 925 }, 8, "כיתה 2/2"));
  game.addUnit(makeInfantry("BLUE-2-3", "BLUE", "squad", { x: 720, y: 935 }, 8, "כיתה 2/3"));
  game.addUnit(makeCommandGroup("BLUE-3-HQ", "BLUE", "platoon", { x: 850, y: 975 }, 3, "חפ\"ק מ\"מ 3"));
  game.addUnit(makeInfantry("BLUE-3-1", "BLUE", "squad", { x: 790, y: 935 }, 8, "כיתה 3/1"));
  game.addUnit(makeInfantry("BLUE-3-2", "BLUE", "squad", { x: 860, y: 925 }, 8, "כיתה 3/2"));
  // The right-hand squad, in the low ground: the eastern face's dead ground is its way up.
  game.addUnit(makeInfantry("BLUE-3-3", "BLUE", "squad", { x: 920, y: 940 }, 8, "כיתה 3/3"));
  // Behind the summit, on its northern side.
  game.addUnit(makeCommandGroup("RED-COY", "RED", "company", { x: 600, y: 200 }, 5, "חפ\"ק מ\"פ"));
  game.addUnit(makeCommandGroup("RED-A-HQ", "RED", "platoon", { x: 570, y: 430 }, 3, "חפ\"ק מ\"מ א'"));
  // The platoon battle's shoulder position, covering the southern approach.
  // Dressed before it is added: addUnit records a force as it stands, so
  // a force camouflaged or covered after the fact would replay undressed.
  const reda1 = makeInfantry("RED-A-1", "RED", "squad", { x: 560, y: 560 }, 8, "מחלקה א'/1");
  reda1.baseCover = "partial";
  game.addUnit(reda1);
  const reda2 = makeInfantry("RED-A-2", "RED", "squad", { x: 650, y: 520 }, 8, "מחלקה א'/2");
  reda2.baseCover = "partial";
  game.addUnit(reda2);
  const reda3 = makeInfantry("RED-A-3", "RED", "squad", { x: 470, y: 510 }, 8, "מחלקה א'/3");
  reda3.baseCover = "partial";
  game.addUnit(reda3);
  game.addUnit(makeCommandGroup("RED-B-HQ", "RED", "platoon", { x: 650, y: 300 }, 3, "חפ\"ק מ\"מ ב'"));
  // On the summit.
  game.addUnit(makeInfantry("RED-B-1", "RED", "squad", { x: 620, y: 350 }, 8, "מחלקה ב'/1"));
  // On the northern spur.
  game.addUnit(makeInfantry("RED-B-2", "RED", "squad", { x: 700, y: 250 }, 6, "מחלקה ב'/2"));
  // On the eastern face, watching the valley.
  game.addUnit(makeInfantry("RED-B-3", "RED", "squad", { x: 760, y: 430 }, 8, "מחלקה ב'/3"));

  // Emplaced in setup, which is the only time a charge is placed rather
  // than laid by a force during the battle (rules decision 16).
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 600, y: 450 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 625, y: 460 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 590, y: 490 }, armed: true, detected: false });

  return { game, mapWidth: 1200, mapHeight: 1000, title: "עמק האלה — פלוגה על תל עזקה" };
}

/** How the scenario picker offers this battle, before anything is built. */
export const telAzekaCompanyListing: ScenarioListing = {
  id: "telAzekaCompany",
  title: "עמק האלה — פלוגה על תל עזקה",
  brief: "כחול: פלוגה תופסת את תל עזקה מדרום. אדום: פלוגה מחזיקה בתל. לפני הקרב כל צד מתכנן את משימתו: מטרות רשומות, תצפיות ועמדות חלופיות.",
  mapWidth: 1200,
  mapHeight: 1000,
  build: buildTelAzekaCompanyScenario,
};
