// Generated by tools/make-scenario.py from tools/scenarios/yokneam-urban.json — do
// not edit by hand; change the spec and rerun the tool. The ground it is laid
// on is generated too, by tools/fetch-dtm.py and tools/fetch-osm.py.
// Written 2026-10-03.

import { Game, makeCommandGroup, makeInfantry, makeVehicle, type Terrain } from "../../engine/index.js";
import type { Scenario, ScenarioListing } from "./types.js";
import { RAMAT_MENASHE } from "../maps/ramatMenashe.js";
import { RAMAT_MENASHE_OBJECTS, RAMAT_MENASHE_ROADS } from "../maps/ramatMenasheObjects.js";

/**
 * The southern edge of Yokneam Illit on Ramat Menashe (יקנעם עילית, רמת מנשה): the town's houses on the hill in the south-east, Route 6 (כביש 6) in the west, low ground to the north.
 * 900 × 800 m centred on 32.64500 N, 35.08500 E, north up.
 */
export function buildYokneamUrbanTerrain(): Terrain {
  return { heightfield: RAMAT_MENASHE, objects: RAMAT_MENASHE_OBJECTS, roads: RAMAT_MENASHE_ROADS };
}

/**
 * The test bed for urban combat (rules decisions 75-78, 2026-10-03): a BLUE
 * company with two tanks and two heavy APCs attacking from the low ground in
 * the north, about 450 m and 80 m of climb, into the north-west edge of the
 * town on the hill, held by a RED platoon in houses it prepared before the
 * battle. Every rule of the day is in play: buildings that are damaged and
 * brought down, rounds through windows, slits and roofs, a tank round that
 * breaches a wall, armour by class and facing, and the RPG.
 *
 * The houses on the town's edge see the low ground; the town behind them
 * sees almost nothing, so RED's reserve and command groups are hidden until
 * the edge is taken. The tanks stand in the low ground in overwatch, where
 * the edge houses are in their sights and out of the RPG's 300 m.
 *
 * ⚠️ Ours, not the author's: the layout, the vehicles' places, and the
 * drill's heavy weapons (a tank fires its main gun out to 1,500 m, a squad
 * its RPG at armour out to 300 m). The APCs carry nobody: passengers are
 * not modelled yet.
 */
export function buildYokneamUrbanScenario(seed = 2027): Scenario {
  const game = new Game({
    seed,
    trackIntel: true,
    enforceC2: true,
    morale: true,
    locationError: true,
    stillDetection: true,
    binoculars: true,
    keepEyesOn: true,
    commandSuccession: true,
    timeLimit: 45,
    attackers: ["BLUE"],
    commandEchelon: { BLUE: "company", RED: "company" },
    fireSupport: {
      BLUE: [{ weapon: "mortar", missions: 12 }],
      RED: [{ weapon: "mortar", missions: 12 }],
    },
    terrain: buildYokneamUrbanTerrain(),
  });

  game.addUnit(makeCommandGroup("BLUE-COY", "BLUE", "company", { x: 450, y: 15 }, 5, "חפ\"ק מ\"פ"));
  game.addUnit(makeCommandGroup("BLUE-1-HQ", "BLUE", "platoon", { x: 330, y: 30 }, 3, "חפ\"ק מ\"מ 1"));
  game.addUnit(makeInfantry("BLUE-1-1", "BLUE", "squad", { x: 280, y: 70 }, 8, "כיתה 1/1"));
  game.addUnit(makeInfantry("BLUE-1-2", "BLUE", "squad", { x: 330, y: 80 }, 8, "כיתה 1/2"));
  game.addUnit(makeInfantry("BLUE-1-3", "BLUE", "squad", { x: 380, y: 75 }, 8, "כיתה 1/3"));
  game.addUnit(makeCommandGroup("BLUE-2-HQ", "BLUE", "platoon", { x: 480, y: 30 }, 3, "חפ\"ק מ\"מ 2"));
  game.addUnit(makeInfantry("BLUE-2-1", "BLUE", "squad", { x: 430, y: 85 }, 8, "כיתה 2/1"));
  game.addUnit(makeInfantry("BLUE-2-2", "BLUE", "squad", { x: 480, y: 90 }, 8, "כיתה 2/2"));
  game.addUnit(makeInfantry("BLUE-2-3", "BLUE", "squad", { x: 530, y: 85 }, 8, "כיתה 2/3"));
  game.addUnit(makeCommandGroup("BLUE-3-HQ", "BLUE", "platoon", { x: 620, y: 40 }, 3, "חפ\"ק מ\"מ 3"));
  game.addUnit(makeInfantry("BLUE-3-1", "BLUE", "squad", { x: 580, y: 95 }, 8, "כיתה 3/1"));
  game.addUnit(makeInfantry("BLUE-3-2", "BLUE", "squad", { x: 630, y: 100 }, 8, "כיתה 3/2"));
  game.addUnit(makeInfantry("BLUE-3-3", "BLUE", "squad", { x: 680, y: 95 }, 8, "כיתה 3/3"));
  // Overwatch from the low ground: sees both edge houses, about 450 m off, at a man's height in full cover.
  game.addUnit(makeVehicle("BLUE-T1", "BLUE", { x: 560, y: 60 }, 90, "טנק 1"));
  game.addUnit(makeVehicle("BLUE-T2", "BLUE", { x: 640, y: 80 }, 90, "טנק 2"));
  game.addUnit(makeVehicle("BLUE-APC1", "BLUE", { x: 380, y: 40 }, 90, "נמר 1", "heavyApc"));
  game.addUnit(makeVehicle("BLUE-APC2", "BLUE", { x: 540, y: 45 }, 90, "נמר 2", "heavyApc"));
  // In a house deep in the town.
  game.addUnit(makeCommandGroup("RED-COY", "RED", "company", { x: 636, y: 565 }, 5, "חפ\"ק מ\"פ"));
  game.addUnit(makeCommandGroup("RED-A-HQ", "RED", "platoon", { x: 569, y: 525 }, 3, "חפ\"ק מ\"מ א'"));
  // The reserve, in a house behind the edge.
  // Dressed before it is added: addUnit records a force as it stands, so
  // a force camouflaged or covered after the fact would replay undressed.
  const reda1 = makeInfantry("RED-A-1", "RED", "squad", { x: 594, y: 546 }, 8, "מחלקה א'/1");
  reda1.baseCover = "full";
  game.addUnit(reda1);
  // At the north face of the edge house that sees most of the low ground.
  const reda2 = makeInfantry("RED-A-2", "RED", "squad", { x: 511, y: 508 }, 8, "מחלקה א'/2");
  reda2.baseCover = "full";
  game.addUnit(reda2);
  const reda3 = makeInfantry("RED-A-3", "RED", "squad", { x: 552, y: 494 }, 8, "מחלקה א'/3");
  reda3.baseCover = "full";
  game.addUnit(reda3);

  // Emplaced in setup, which is the only time a charge is placed rather
  // than laid by a force during the battle (rules decision 16).
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 520, y: 470 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 560, y: 460 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiTank", position: { x: 540, y: 440 }, armed: true, detected: false });

  return { game, mapWidth: 900, mapHeight: 800, title: "יקנעם — לחימה בשטח בנוי", reserves: ["RED-A-1"] };
}

/** How the scenario picker offers this battle, before anything is built. */
export const yokneamUrbanListing: ScenarioListing = {
  id: "yokneamUrban",
  title: "יקנעם — לחימה בשטח בנוי",
  brief: "כחול: פלוגה עם טנקים ונגמ\"שים תוקפת מהשטח הנמוך בצפון אל שולי השכונה שעל הגבעה. אדום: מחלקה מחזיקה בבתים בשולי השכונה, בעמדות שהוכנו מראש. לפני הקרב כל צד מתכנן את משימתו. יש להשלים את המשימה עד תור 45.",
  mapWidth: 900,
  mapHeight: 800,
  build: buildYokneamUrbanScenario,
};
