// Generated by tools/make-scenario.py from tools/scenarios/yokneam-raid.json — do
// not edit by hand; change the spec and rerun the tool. The ground it is laid
// on is generated too, by tools/fetch-dtm.py and tools/fetch-osm.py.
// Written 2026-10-06.

import { Game, forceQuality, makeCommandGroup, makeInfantry, makeVehicle, type Terrain } from "../../engine/index.js";
import type { Scenario, ScenarioListing } from "./types.js";
import { RAMAT_MENASHE } from "../maps/ramatMenashe.js";
import { RAMAT_MENASHE_OBJECTS, RAMAT_MENASHE_ROADS } from "../maps/ramatMenasheObjects.js";

/**
 * The southern edge of Yokneam Illit on Ramat Menashe (יקנעם עילית, רמת מנשה): the town's houses on the hill in the south-east, Route 6 (כביש 6) in the west, low ground to the north.
 * 900 × 800 m centred on 32.64500 N, 35.08500 E, north up.
 */
export function buildYokneamRaidTerrain(): Terrain {
  return { heightfield: RAMAT_MENASHE, objects: RAMAT_MENASHE_OBJECTS, roads: RAMAT_MENASHE_ROADS };
}

/**
 * A raid without support weapons (the author, 2026-10-04: the quality gap
 * "especially in special operations where artillery and other support
 * weapons aren't involved — e.g. Black Hawk Down type scenarios"): an elite,
 * very experienced BLUE platoon of three teams, already inserted into houses
 * in the east of the town, raids the block 100-150 m west of it, held by an
 * irregular militia of six squads in its houses, nearly two to one.
 * No mortars, no vehicles: small arms, rifle grenades and the assault, where
 * the quality gap (rules decision 84) counts for most.
 *
 * The militia holds the houses that see the low ground with four squads and
 * keeps two behind them, each retaking a lost house by the drill (decision
 * 60). It has barricaded them in haste (partial cover, facing the low ground in
 * the north it expects an attack from); the houses themselves cover all round.
 * The raid comes from the east, outside the arc it watches (decision 85).
 *
 * Measured (docs/balance.md, sixtieth round): the harness's scripted attack
 * is built for open ground and stalls in the town, so the raid is judged in play.
 *
 * ⚠️ Ours, not the author's: the layout, the strengths, the militia's
 * cell (irregular, experienced) and the 30-turn time limit.
 */
export function buildYokneamRaidScenario(seed = 2031): Scenario {
  const game = new Game({
    seed,
    trackIntel: true,
    enforceC2: true,
    morale: true,
    locationError: true,
    stillDetection: true,
    binoculars: true,
    keepEyesOn: true,
    commandSuccession: true,
    timeLimit: 30,
    attackers: ["BLUE"],
    commandEchelon: { BLUE: "platoon", RED: "company" },
    terrain: buildYokneamRaidTerrain(),
  });

  // Dressed before it is added: addUnit records a force as it stands, so
  // a force camouflaged or covered after the fact would replay undressed.
  const blue1hq = makeCommandGroup("BLUE-1-HQ", "BLUE", "platoon", { x: 729, y: 564 }, 3, "חפ\"ק הכוח");
  Object.assign(blue1hq, forceQuality({ type: "elite", experience: "veryExperienced" }));
  game.addUnit(blue1hq);
  const blue11 = makeInfantry("BLUE-1-1", "BLUE", "squad", { x: 718, y: 510 }, 8, "צוות 1");
  Object.assign(blue11, forceQuality({ type: "elite", experience: "veryExperienced" }));
  game.addUnit(blue11);
  const blue12 = makeInfantry("BLUE-1-2", "BLUE", "squad", { x: 722, y: 529 }, 8, "צוות 2");
  Object.assign(blue12, forceQuality({ type: "elite", experience: "veryExperienced" }));
  game.addUnit(blue12);
  const blue13 = makeInfantry("BLUE-1-3", "BLUE", "squad", { x: 725, y: 546 }, 8, "צוות 3");
  Object.assign(blue13, forceQuality({ type: "elite", experience: "veryExperienced" }));
  game.addUnit(blue13);
  // In a house deep in the town.
  const redcoy = makeCommandGroup("RED-COY", "RED", "company", { x: 636, y: 565 }, 3, "מפקד המיליציה");
  Object.assign(redcoy, forceQuality({ type: "irregular", experience: "experienced" }));
  redcoy.readiness = 1;
  game.addUnit(redcoy);
  // The edge houses that see the low ground.
  const reda1 = makeInfantry("RED-A-1", "RED", "squad", { x: 582, y: 474 }, 7, "חוליה א'/1");
  Object.assign(reda1, forceQuality({ type: "irregular", experience: "experienced" }));
  reda1.baseCover = "partial";
  reda1.front = 255;
  reda1.readiness = 1;
  game.addUnit(reda1);
  const reda2 = makeInfantry("RED-A-2", "RED", "squad", { x: 529, y: 510 }, 7, "חוליה א'/2");
  Object.assign(reda2, forceQuality({ type: "irregular", experience: "experienced" }));
  reda2.baseCover = "partial";
  reda2.front = 263;
  reda2.readiness = 1;
  game.addUnit(reda2);
  // Behind the edge: retakes a lost house.
  const reda3 = makeInfantry("RED-A-3", "RED", "squad", { x: 569, y: 525 }, 7, "חוליה א'/3");
  Object.assign(reda3, forceQuality({ type: "irregular", experience: "experienced" }));
  reda3.baseCover = "partial";
  reda3.front = 259;
  reda3.readiness = 1;
  game.addUnit(reda3);
  const redb1 = makeInfantry("RED-B-1", "RED", "squad", { x: 644, y: 484 }, 7, "חוליה ב'/1");
  Object.assign(redb1, forceQuality({ type: "irregular", experience: "experienced" }));
  redb1.baseCover = "partial";
  redb1.front = 248;
  redb1.readiness = 1;
  game.addUnit(redb1);
  const redb2 = makeInfantry("RED-B-2", "RED", "squad", { x: 602, y: 479 }, 7, "חוליה ב'/2");
  Object.assign(redb2, forceQuality({ type: "irregular", experience: "experienced" }));
  redb2.baseCover = "partial";
  redb2.front = 253;
  redb2.readiness = 1;
  game.addUnit(redb2);
  const redb3 = makeInfantry("RED-B-3", "RED", "squad", { x: 638, y: 525 }, 7, "חוליה ב'/3");
  Object.assign(redb3, forceQuality({ type: "irregular", experience: "experienced" }));
  redb3.baseCover = "partial";
  redb3.front = 250;
  redb3.readiness = 1;
  game.addUnit(redb3);

  return { game, mapWidth: 900, mapHeight: 800, title: "יקנעם — פשיטה", reserves: ["RED-A-3", "RED-B-3"] };
}

/** How the scenario picker offers this battle, before anything is built. */
export const yokneamRaidListing: ScenarioListing = {
  id: "yokneamRaid",
  title: "יקנעם — פשיטה",
  brief: "כחול: כוח מיוחד שהונחת בבתים במזרח השכונה פושט על בלוק הבתים שממערב לו, בלי סיוע אש. אדום: מחזיק בבלוק הבתים. לפני הקרב כל צד מתכנן את משימתו. יש להשלים את המשימה עד תור 30.",
  mapWidth: 900,
  mapHeight: 800,
  build: buildYokneamRaidScenario,
};
