// Generated by tools/make-scenario.py from tools/scenarios/yokneam-illit.json — do
// not edit by hand; change the spec and rerun the tool. The ground it is laid
// on is generated too, by tools/fetch-dtm.py and tools/fetch-osm.py.
// Written 2026-09-16.

import { CAMOUFLAGE_TURNS_AT_MAX, Game, makeCommandGroup, makeInfantry, makeVehicle, type Terrain } from "../../engine/index.js";
import type { Scenario } from "./types.js";
import { RAMAT_MENASHE } from "../maps/ramatMenashe.js";
import { RAMAT_MENASHE_OBJECTS, RAMAT_MENASHE_ROADS } from "../maps/ramatMenasheObjects.js";

/**
 * The southern edge of Yokneam Illit on Ramat Menashe (יקנעם עילית, רמת מנשה): the town's houses on the hill in the south-east, Route 6 (כביש 6) in the west, low ground to the north.
 * 900 × 800 m centred on 32.64500 N, 35.08500 E, north up.
 */
export function buildYokneamIllitTerrain(): Terrain {
  return { heightfield: RAMAT_MENASHE, objects: RAMAT_MENASHE_OBJECTS, roads: RAMAT_MENASHE_ROADS };
}

/**
 * A small hotseat demonstration: a BLUE infantry platoon in the low ground to
 * the north attacking a RED position on the town's edge to the south, held by
 * two squads and a tank. The hill's shoulder hides the slope below it from
 * every RED position, so BLUE's first bound is unseen and it comes into view
 * as it reaches the shoulder — to the forward squad, the flank squad on the
 * north-east ridge and the tank alike.
 *
 * One lesson the ground teaches on its own: the tank's hatches see over the
 * shoulder to the far low ground where BLUE starts, 440 m off, and not the
 * slope just below it where the attack actually climbs — dead ground is
 * nearer than it looks.
 *
 * The player is the platoon leader: they manoeuvre the squads and control
 * their own command group. Played with the knowledge model on, so each side
 * sees what it has detected — the document's own rolls — rather than
 * everything within a radius.
 *
 * RED's forward squad lies on the shoulder in the open and prepared its
 * position before the battle, so it starts fully camouflaged (rules decision
 * 12): BLUE will not find it by looking. It is also the one force here that
 * lays charges during the battle (rules decision 16) — the rule gives that
 * work to an insurgent or special force, and until force types arrive with
 * echelon scaling the scenario is what says which force is one.
 *
 * ⚠️ That last part is ours, not the author's: the demo's RED is a
 * conventional platoon, and the flag is here so the rule can be played
 * rather than only tested. One line to delete when force types land.
 */
export function buildYokneamIllitScenario(seed = 2026): Scenario {
  const game = new Game({
    seed,
    trackIntel: true,
    enforceC2: true,
    terrain: buildYokneamIllitTerrain(),
  });

  game.addUnit(makeInfantry("BLUE-1", "BLUE", "squad", { x: 250, y: 80 }, 8, "כיתה 1"));
  game.addUnit(makeInfantry("BLUE-2", "BLUE", "squad", { x: 400, y: 60 }, 8, "כיתה 2"));
  game.addUnit(makeInfantry("BLUE-3", "BLUE", "squad", { x: 460, y: 70 }, 8, "כיתה 3"));
  game.addUnit(makeCommandGroup("BLUE-HQ", "BLUE", "platoon", { x: 400, y: 20 }, 3, "חפ\"ק מ\"מ"));
  // Dressed before it is added: addUnit records a force as it stands, so
  // a force camouflaged or covered after the fact would replay undressed.
  const red1 = makeInfantry("RED-1", "RED", "squad", { x: 380, y: 336 }, 6, "מחלקה א'/1");
  red1.camouflaging = true;
  red1.camouflageTurns = CAMOUFLAGE_TURNS_AT_MAX;
  red1.canLayCharges = true;
  game.addUnit(red1);
  // The second squad holds the ridge coming down from the north-east, on the flank of the axis.
  game.addUnit(makeInfantry("RED-2", "RED", "squad", { x: 700, y: 260 }, 8, "מחלקה א'/2"));
  // In a street on the hilltop behind the crest. It stands 4.6 m from the nearest house — outside the 3 m cover reach on purpose, since full cover would drop its eye to 0.5 m and switch the far-low-ground lesson off (src/app/scenario.test.ts pins it).
  game.addUnit(makeVehicle("RED-TANK", "RED", { x: 520, y: 500 }, 270, "טנק"));
  // In one of the houses on the reverse slope: it sees none of the shoulder.
  game.addUnit(makeCommandGroup("RED-HQ", "RED", "platoon", { x: 436, y: 599 }, 3, "חפ\"ק מ\"מ"));

  // Emplaced in setup, which is the only time a charge is placed rather
  // than laid by a force during the battle (rules decision 16).
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 330, y: 240 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 400, y: 230 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 470, y: 250 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiPersonnel", position: { x: 560, y: 230 }, armed: true, detected: false });
  game.addMine({ side: "RED", type: "antiTank", position: { x: 450, y: 300 }, armed: true, detected: false });

  return { game, mapWidth: 900, mapHeight: 800, title: "תרגיל הדגמה — מגע ראשון" };
}
